kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.0.0
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv $GOPATH/bin/kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              subPath: kustomize
              mountPath: /usr/local/bin/kustomize
            - name: custom-tools
              subPath: ksops
              mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
            - name: sops-age
              subPath: sops-age.txt
              mountPath: /home/argocd/.age/sops-age.txt
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/.age/sops-age.txt
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: age-home
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
