kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.0.0
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv $GOPATH/bin/kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
        - name: import-gpg-key
          image: argoproj/argocd:v2.5.8
          command: ["gpg", "--import", "/sops-gpg/sops.asc"]
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          volumeMounts:
            - name: sops-gpg
              mountPath: /sops-gpg
            - name: gnupg-home
              mountPath: /gnupg-home
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              subPath: kustomize
              mountPath: /usr/local/bin/kustomize
            - name: custom-tools
              subPath: ksops
              mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
            - name: gnupg-home
              subPath: .gnupg
              mountPath: /home/argocd/.gnupg
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: GNUPGHOME
              value: /home/argocd/.gnupg
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: gnupg-home
          emptyDir: {}
        - name: sops-gpg
          secret:
            secretName: sops-gpg
