name: Deploy  ## .

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Environment
        run: |
          if [[ ${{ github.ref_name }} == *-staging ]]; then
            export ENVIRONMENT=staging
          else
            export ENVIRONMENT=production
          fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "==== Deploy to $ENVIRONMENT"

      - name: Check Deployment Image Version
        run: |
          git pull origin CA-9:CA-9

          IMAGE_VERSION=$(cat .k8s/${{ env.ENVIRONMENT }}/deployment.yml | awk "/image:/ {print $2}" | sed "s/.*.cart-api.//")

          if [[ $IMAGE_VERSION == ${{ github.ref_name }} ]]; then
            echo "==== Ok"
          else
            echo "==== Error: Image version is different from tag."
            exit 1
          fi

      - name: Test
        run: |
          echo "--------------"
          echo ${{ github.ref_name }}
          echo ${{ github.base_ref }}
          echo ${{ github.event.ref_name }}
          echo ${{ github.event.base_ref }}
          echo "--------------"

