name: Deploy  ## .

on:
  workflow_call:
    inputs:
      deploy-file:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Environment
        run: |
          if [[ ${{ github.ref_name }} == *-staging ]]; then
            export ENVIRONMENT=staging
          else
            export ENVIRONMENT=production
          fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "==== Deploy to $ENVIRONMENT"

      - name: Check Deployment Image Version
        run: |
          echo "------------"
          echo ${{ inputs.deploy-file }}
          echo "------------"

