name: Deploy  ## .

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        run: |
        echo "--------------"
        echo ${{ secrets.ARGOCD_USERNAME }}
        echo ${{ secrets.DOCKERHUB_TOKEN }}
        echo "--------------"